CAEN V8100 SDK: V8100.c File Reference
V8100.c File Reference
V8100 VME board implementation.
#include <string.h>
#include <memory.h>
#include <stdlib.h>
#include "V8100.h"
Functions
BOOL V8100_open_com (V8100_data *p_data, const char *com_str, V8100_RS232_BITRATE bitrate)
V8100 boards data initialization and serial communication device opening.
BOOL V8100_open_eth (V8100_data *p_data, const char *ip_add)
V8100 boards data initialization and socket communication device opening.
BOOL V8100_close (V8100_data *p_data)
V8100 boards closing and resource free.
BOOL V8100_mon_name (V8100_data *p_data, UINT8 ch_id, char *value, int value_size, CMD_ERROR_CODE *error_code)
Gets the channel name.
BOOL V8100_mon_vset (V8100_data *p_data, UINT8 ch_id, float *value, CMD_ERROR_CODE *error_code)
Gets the value of the voltage Set.
BOOL V8100_mon_vmin (V8100_data *p_data, UINT8 ch_id, float *value, CMD_ERROR_CODE *error_code)
Gets the minimum value of the voltage Set.
BOOL V8100_mon_vmax (V8100_data *p_data, UINT8 ch_id, float *value, CMD_ERROR_CODE *error_code)
Gets the maximum value of the voltage Set.
BOOL V8100_mon_vres (V8100_data *p_data, UINT8 ch_id, float *value, CMD_ERROR_CODE *error_code)
Gets the resolution value of the voltage Set.
BOOL V8100_mon_ovp (V8100_data *p_data, UINT8 ch_id, float *value, CMD_ERROR_CODE *error_code)
Gets the value of the Over Voltage Protection.
BOOL V8100_mon_uvp (V8100_data *p_data, UINT8 ch_id, float *value, CMD_ERROR_CODE *error_code)
Gets the value of the Under Voltage Protection.
BOOL V8100_mon_vmon (V8100_data *p_data, UINT8 ch_id, float *value, CMD_ERROR_CODE *error_code)
Gets the value of the voltage Monitor.
BOOL V8100_mon_iset (V8100_data *p_data, UINT8 ch_id, float *value, CMD_ERROR_CODE *error_code)
Gets the value of the current limit.
BOOL V8100_mon_imin (V8100_data *p_data, UINT8 ch_id, float *value, CMD_ERROR_CODE *error_code)
Gets the minimum value of current limit.
BOOL V8100_mon_imax (V8100_data *p_data, UINT8 ch_id, float *value, CMD_ERROR_CODE *error_code)
Gets the maximum value of current limit.
BOOL V8100_mon_ires (V8100_data *p_data, UINT8 ch_id, float *value, CMD_ERROR_CODE *error_code)
Gets the resolution of current limit.
BOOL V8100_mon_imon (V8100_data *p_data, UINT8 ch_id, float *value, CMD_ERROR_CODE *error_code)
Gets the value of the current Monitor.
BOOL V8100_mon_stat (V8100_data *p_data, UINT8 ch_id, V8100_channel_status *value, CMD_ERROR_CODE *error_code)
Gets the value of the channel status.
BOOL V8100_set_vset (V8100_data *p_data, UINT8 ch_id, float value, CMD_ERROR_CODE *error_code)
Sets the value of voltage.
BOOL V8100_set_iset (V8100_data *p_data, UINT8 ch_id, float value, CMD_ERROR_CODE *error_code)
Sets the value of current limit.
BOOL V8100_set_ovp (V8100_data *p_data, UINT8 ch_id, UINT8 value, CMD_ERROR_CODE *error_code)
Sets the value of Value OVP (as % di Vset).
BOOL V8100_set_uvp (V8100_data *p_data, UINT8 ch_id, UINT8 value, CMD_ERROR_CODE *error_code)
Sets the value of Value UVP (as % di Vset).
BOOL V8100_mon_crname (V8100_data *p_data, char *value, int value_size, CMD_ERROR_CODE *error_code)
Gets the crate name.
BOOL V8100_mon_numch (V8100_data *p_data, UINT8 *value, CMD_ERROR_CODE *error_code)
Gets the value of the voltage Set.
BOOL V8100_mon_psfrel (V8100_data *p_data, char *value, int value_size, CMD_ERROR_CODE *error_code)
Gets the PS Release Firmware.
BOOL V8100_mon_pstemp (V8100_data *p_data, float *value, CMD_ERROR_CODE *error_code)
Gets the value of the PS Temperature.
BOOL V8100_mon_pssnum (V8100_data *p_data, UINT32 *value, CMD_ERROR_CODE *error_code)
Gets the value of the PS Serial Number.
BOOL V8100_mon_fansp (V8100_data *p_data, V8100_FAN_SPEED_SET *value, CMD_ERROR_CODE *error_code)
Gets the Set value of FAN SPEED _V8100_FAN_SPEED_SET.
BOOL V8100_mon_fan1 (V8100_data *p_data, UINT32 *value, CMD_ERROR_CODE *error_code)
Gets the value of the Fan Speed 1 (RPM).
BOOL V8100_mon_fan2 (V8100_data *p_data, UINT32 *value, CMD_ERROR_CODE *error_code)
Gets the value of the Fan Speed 2 (RPM).
BOOL V8100_mon_fan3 (V8100_data *p_data, UINT32 *value, CMD_ERROR_CODE *error_code)
Gets the value of the Fan Speed 3 (RPM).
BOOL V8100_mon_fufrel (V8100_data *p_data, char *value, int value_size, CMD_ERROR_CODE *error_code)
Gets the FAN UNIT Release Firmware.
BOOL V8100_mon_futemp (V8100_data *p_data, float *value, CMD_ERROR_CODE *error_code)
Gets the value of the FAN UNIT Temperature.
BOOL V8100_mon_fusnum (V8100_data *p_data, UINT32 *value, CMD_ERROR_CODE *error_code)
Gets the value of the FAN UNIT Serial Number.
BOOL V8100_mon_crst (V8100_data *p_data, V8100_crate_status *value, CMD_ERROR_CODE *error_code)
Gets the value of the crate status.
BOOL V8100_mon_vpmax (V8100_data *p_data, float *value, CMD_ERROR_CODE *error_code)
Gets the value maximum of OVP/UVP.
BOOL V8100_mon_vpmin (V8100_data *p_data, float *value, CMD_ERROR_CODE *error_code)
Gets the value minimum of OVP/UVP.
BOOL V8100_mon_rs232br (V8100_data *p_data, V8100_RS232_BITRATE *value, CMD_ERROR_CODE *error_code)
Gets the value of Bit Rate RS232 : _V8100_RS232_BITRATE.
BOOL V8100_mon_canbr (V8100_data *p_data, V8100_CANBUS_BITRATE *value, CMD_ERROR_CODE *error_code)
Gets the value of Bit Rate CANBUS : _V8100_CANBUS_BITRATE.
BOOL V8100_mon_canadd (V8100_data *p_data, UINT8 *value, CMD_ERROR_CODE *error_code)
Gets the Address CANBUS : 0..255.
BOOL V8100_mon_ipadd (V8100_data *p_data, char *value, int value_size, CMD_ERROR_CODE *error_code)
Gets the Address IP : xxx.xxx.xxx.xxx.
BOOL V8100_mon_ipmsk (V8100_data *p_data, char *value, int value_size, CMD_ERROR_CODE *error_code)
Gets the IP Netmask : xxx.xxx.xxx.xxx.
BOOL V8100_mon_ipgtw (V8100_data *p_data, char *value, int value_size, CMD_ERROR_CODE *error_code)
Gets the Gateway : xxx.xxx.xxx.xxx.
BOOL V8100_mon_macadd (V8100_data *p_data, char *value, int value_size, CMD_ERROR_CODE *error_code)
Gets the Mac Address : xx.xx.xx.xx.xx.xx.
BOOL V8100_set_on (V8100_data *p_data, CMD_ERROR_CODE *error_code)
Switches the crate ON.
BOOL V8100_set_off (V8100_data *p_data, CMD_ERROR_CODE *error_code)
Switches the crate OFF.
BOOL V8100_set_sysr (V8100_data *p_data, CMD_ERROR_CODE *error_code)
Sends VME System Reset.
BOOL V8100_set_clr (V8100_data *p_data, CMD_ERROR_CODE *error_code)
Clear Alarm.
BOOL V8100_set_fansp (V8100_data *p_data, V8100_FAN_SPEED_SET value, CMD_ERROR_CODE *error_code)
Set Fan Speed _V8100_FAN_SPEED_SET.
const char * V8100_SW_rev (void)
Returns the SDK software release.
Detailed Description
V8100 VME board implementation.
Author:
NDA
Version:
1.0
Date:
09/2008
Provides methods, properties and defines to handle V8100 VME boards
Definition in file V8100.c.
Function Documentation
BOOL V8100_close (V8100_data * p_data)
V8100 boards closing and resource free.
Provides specific handling for V8100 boards closing.
Parameters:
p_data Pointer to board data
Returns:
TRUE: board successfully closed
Note:
Must be called when done with any other board specific API.
Definition at line 183 of file V8100.c.
References board_close(), and V8100_data::m_common_data.
BOOL V8100_mon_canadd (V8100_data * p_data, UINT8 * value, CMD_ERROR_CODE * error_code)
Gets the Address CANBUS : 0..255.
Parameters:
p_data Pointer to board data
value The pointer to the read value
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 492 of file V8100.c.
References V8100_data::m_common_data, send_cmd(), V8100_CMD_CR_MON_CANADD, and V8100_CR_CH_ID.
BOOL V8100_mon_canbr (V8100_data * p_data, V8100_CANBUS_BITRATE * value, CMD_ERROR_CODE * error_code)
Gets the value of Bit Rate CANBUS : _V8100_CANBUS_BITRATE.
Parameters:
p_data Pointer to board data
value The pointer to the read value
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 482 of file V8100.c.
References V8100_data::m_common_data, send_cmd(), V8100_CMD_CR_MON_CANBR, and V8100_CR_CH_ID.
BOOL V8100_mon_crname (V8100_data * p_data, char * value, int value_size, CMD_ERROR_CODE * error_code)
Gets the crate name.
Parameters:
p_data Pointer to board data
value The read value buffer (caller allocated)
value_size The value buffer size (BYTEs)
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 343 of file V8100.c.
References V8100_data::m_common_data, send_cmd(), V8100_CMD_CR_MON_CRNAME, and V8100_CR_CH_ID.
BOOL V8100_mon_crst (V8100_data * p_data, V8100_crate_status * value, CMD_ERROR_CODE * error_code)
Gets the value of the crate status.
Parameters:
p_data Pointer to board data
value The pointer to the read value (V8100_crate_status)
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 448 of file V8100.c.
References V8100_data::m_common_data, V8100_crate_status::m_word, send_cmd(), V8100_CMD_CR_MON_CRST, and V8100_CR_CH_ID.
BOOL V8100_mon_fan1 (V8100_data * p_data, UINT32 * value, CMD_ERROR_CODE * error_code)
Gets the value of the Fan Speed 1 (RPM).
Parameters:
p_data Pointer to board data
value The pointer to the read value
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 394 of file V8100.c.
References V8100_data::m_common_data, send_cmd(), V8100_CMD_CR_MON_FAN1, and V8100_CR_CH_ID.
BOOL V8100_mon_fan2 (V8100_data * p_data, UINT32 * value, CMD_ERROR_CODE * error_code)
Gets the value of the Fan Speed 2 (RPM).
Parameters:
p_data Pointer to board data
value The pointer to the read value
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 404 of file V8100.c.
References V8100_data::m_common_data, send_cmd(), V8100_CMD_CR_MON_FAN2, and V8100_CR_CH_ID.
BOOL V8100_mon_fan3 (V8100_data * p_data, UINT32 * value, CMD_ERROR_CODE * error_code)
Gets the value of the Fan Speed 3 (RPM).
Parameters:
p_data Pointer to board data
value The pointer to the read value
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 414 of file V8100.c.
References V8100_data::m_common_data, send_cmd(), V8100_CMD_CR_MON_FAN3, and V8100_CR_CH_ID.
BOOL V8100_mon_fansp (V8100_data * p_data, V8100_FAN_SPEED_SET * value, CMD_ERROR_CODE * error_code)
Gets the Set value of FAN SPEED _V8100_FAN_SPEED_SET.
Parameters:
p_data Pointer to board data
value The pointer to the read value
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 384 of file V8100.c.
References V8100_data::m_common_data, send_cmd(), V8100_CMD_CR_MON_FANSP, and V8100_CR_CH_ID.
BOOL V8100_mon_fufrel (V8100_data * p_data, char * value, int value_size, CMD_ERROR_CODE * error_code)
Gets the FAN UNIT Release Firmware.
Parameters:
p_data Pointer to board data
value The read value buffer (caller allocated)
value_size The value buffer size (BYTEs)
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 424 of file V8100.c.
References V8100_data::m_common_data, send_cmd(), V8100_CMD_CR_MON_FUFREL, and V8100_CR_CH_ID.
BOOL V8100_mon_fusnum (V8100_data * p_data, UINT32 * value, CMD_ERROR_CODE * error_code)
Gets the value of the FAN UNIT Serial Number.
Parameters:
p_data Pointer to board data
value The pointer to the read value
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 438 of file V8100.c.
References V8100_data::m_common_data, send_cmd(), V8100_CMD_CR_MON_FUSNUM, and V8100_CR_CH_ID.
BOOL V8100_mon_futemp (V8100_data * p_data, float * value, CMD_ERROR_CODE * error_code)
Gets the value of the FAN UNIT Temperature.
Parameters:
p_data Pointer to board data
value The pointer to the read value
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 431 of file V8100.c.
References V8100_data::m_common_data, send_cmd(), V8100_CMD_CR_MON_FUTEMP, and V8100_CR_CH_ID.
BOOL V8100_mon_imax (V8100_data * p_data, UINT8 ch_id, float * value, CMD_ERROR_CODE * error_code)
Gets the maximum value of current limit.
Parameters:
p_data Pointer to board data
ch_id The channel identifier
value The pointer to the read value
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 273 of file V8100.c.
References V8100_data::m_common_data, send_cmd(), and V8100_CMD_CH_MON_IMAX.
BOOL V8100_mon_imin (V8100_data * p_data, UINT8 ch_id, float * value, CMD_ERROR_CODE * error_code)
Gets the minimum value of current limit.
Parameters:
p_data Pointer to board data
ch_id The channel identifier
value The pointer to the read value
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 266 of file V8100.c.
References V8100_data::m_common_data, send_cmd(), and V8100_CMD_CH_MON_IMIN.
BOOL V8100_mon_imon (V8100_data * p_data, UINT8 ch_id, float * value, CMD_ERROR_CODE * error_code)
Gets the value of the current Monitor.
Parameters:
p_data Pointer to board data
ch_id The channel identifier
value The pointer to the read value
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 287 of file V8100.c.
References V8100_data::m_common_data, send_cmd(), and V8100_CMD_CH_MON_IMON.
BOOL V8100_mon_ipadd (V8100_data * p_data, char * value, int value_size, CMD_ERROR_CODE * error_code)
Gets the Address IP : xxx.xxx.xxx.xxx.
Parameters:
p_data Pointer to board data
value The read value buffer (caller allocated)
value_size The value buffer size (BYTEs)
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 502 of file V8100.c.
References V8100_data::m_common_data, send_cmd(), V8100_CMD_CR_MON_IPADD, and V8100_CR_CH_ID.
BOOL V8100_mon_ipgtw (V8100_data * p_data, char * value, int value_size, CMD_ERROR_CODE * error_code)
Gets the Gateway : xxx.xxx.xxx.xxx.
Parameters:
p_data Pointer to board data
value The read value buffer (caller allocated)
value_size The value buffer size (BYTEs)
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 516 of file V8100.c.
References V8100_data::m_common_data, send_cmd(), V8100_CMD_CR_MON_IPGTW, and V8100_CR_CH_ID.
BOOL V8100_mon_ipmsk (V8100_data * p_data, char * value, int value_size, CMD_ERROR_CODE * error_code)
Gets the IP Netmask : xxx.xxx.xxx.xxx.
Parameters:
p_data Pointer to board data
value The read value buffer (caller allocated)
value_size The value buffer size (BYTEs)
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 509 of file V8100.c.
References V8100_data::m_common_data, send_cmd(), V8100_CMD_CR_MON_IPMSK, and V8100_CR_CH_ID.
BOOL V8100_mon_ires (V8100_data * p_data, UINT8 ch_id, float * value, CMD_ERROR_CODE * error_code)
Gets the resolution of current limit.
Parameters:
p_data Pointer to board data
ch_id The channel identifier
value The pointer to the read value
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 280 of file V8100.c.
References V8100_data::m_common_data, send_cmd(), and V8100_CMD_CH_MON_IRES.
BOOL V8100_mon_iset (V8100_data * p_data, UINT8 ch_id, float * value, CMD_ERROR_CODE * error_code)
Gets the value of the current limit.
Parameters:
p_data Pointer to board data
ch_id The channel identifier
value The pointer to the read value
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 259 of file V8100.c.
References V8100_data::m_common_data, send_cmd(), and V8100_CMD_CH_MON_ISET.
BOOL V8100_mon_macadd (V8100_data * p_data, char * value, int value_size, CMD_ERROR_CODE * error_code)
Gets the Mac Address : xx.xx.xx.xx.xx.xx.
Parameters:
p_data Pointer to board data
value The read value buffer (caller allocated)
value_size The value buffer size (BYTEs)
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 523 of file V8100.c.
References V8100_data::m_common_data, send_cmd(), V8100_CMD_CR_MON_MACADD, and V8100_CR_CH_ID.
BOOL V8100_mon_name (V8100_data * p_data, UINT8 ch_id, char * value, int value_size, CMD_ERROR_CODE * error_code)
Gets the channel name.
Parameters:
p_data Pointer to board data
ch_id The channel identifier
value The read value buffer (caller allocated)
value_size The value buffer size (BYTEs)
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 203 of file V8100.c.
References V8100_data::m_common_data, send_cmd(), and V8100_CMD_CH_MON_NAME.
BOOL V8100_mon_numch (V8100_data * p_data, UINT8 * value, CMD_ERROR_CODE * error_code)
Gets the value of the voltage Set.
Parameters:
p_data Pointer to board data
value The pointer to the read value
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 350 of file V8100.c.
References V8100_data::m_common_data, send_cmd(), V8100_CMD_CR_MON_NUMCH, and V8100_CR_CH_ID.
BOOL V8100_mon_ovp (V8100_data * p_data, UINT8 ch_id, float * value, CMD_ERROR_CODE * error_code)
Gets the value of the Over Voltage Protection.
Parameters:
p_data Pointer to board data
ch_id The channel identifier
value The pointer to the read value
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 238 of file V8100.c.
References V8100_data::m_common_data, send_cmd(), and V8100_CMD_CH_MON_OVP.
BOOL V8100_mon_psfrel (V8100_data * p_data, char * value, int value_size, CMD_ERROR_CODE * error_code)
Gets the PS Release Firmware.
Parameters:
p_data Pointer to board data
value The read value buffer (caller allocated)
value_size The value buffer size (BYTEs)
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 360 of file V8100.c.
References V8100_data::m_common_data, send_cmd(), V8100_CMD_CR_MON_PSFREL, and V8100_CR_CH_ID.
BOOL V8100_mon_pssnum (V8100_data * p_data, UINT32 * value, CMD_ERROR_CODE * error_code)
Gets the value of the PS Serial Number.
Parameters:
p_data Pointer to board data
value The pointer to the read value
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 374 of file V8100.c.
References V8100_data::m_common_data, send_cmd(), V8100_CMD_CR_MON_PSSNUM, and V8100_CR_CH_ID.
BOOL V8100_mon_pstemp (V8100_data * p_data, float * value, CMD_ERROR_CODE * error_code)
Gets the value of the PS Temperature.
Parameters:
p_data Pointer to board data
value The pointer to the read value
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 367 of file V8100.c.
References V8100_data::m_common_data, send_cmd(), V8100_CMD_CR_MON_PSTEMP, and V8100_CR_CH_ID.
BOOL V8100_mon_rs232br (V8100_data * p_data, V8100_RS232_BITRATE * value, CMD_ERROR_CODE * error_code)
Gets the value of Bit Rate RS232 : _V8100_RS232_BITRATE.
Parameters:
p_data Pointer to board data
value The pointer to the read value
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 472 of file V8100.c.
References V8100_data::m_common_data, send_cmd(), V8100_CMD_CR_MON_RS232BR, and V8100_CR_CH_ID.
BOOL V8100_mon_stat (V8100_data * p_data, UINT8 ch_id, V8100_channel_status * value, CMD_ERROR_CODE * error_code)
Gets the value of the channel status.
Parameters:
p_data Pointer to board data
ch_id The channel identifier
value The pointer to the read value (V8100_channel_status)
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 294 of file V8100.c.
References V8100_data::m_common_data, V8100_channel_status::m_word, send_cmd(), and V8100_CMD_CH_MON_STAT.
BOOL V8100_mon_uvp (V8100_data * p_data, UINT8 ch_id, float * value, CMD_ERROR_CODE * error_code)
Gets the value of the Under Voltage Protection.
Parameters:
p_data Pointer to board data
ch_id The channel identifier
value The pointer to the read value
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 245 of file V8100.c.
References V8100_data::m_common_data, send_cmd(), and V8100_CMD_CH_MON_UVP.
BOOL V8100_mon_vmax (V8100_data * p_data, UINT8 ch_id, float * value, CMD_ERROR_CODE * error_code)
Gets the maximum value of the voltage Set.
Parameters:
p_data Pointer to board data
ch_id The channel identifier
value The pointer to the read value
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 224 of file V8100.c.
References V8100_data::m_common_data, send_cmd(), and V8100_CMD_CH_MON_VMAX.
BOOL V8100_mon_vmin (V8100_data * p_data, UINT8 ch_id, float * value, CMD_ERROR_CODE * error_code)
Gets the minimum value of the voltage Set.
Parameters:
p_data Pointer to board data
ch_id The channel identifier
value The pointer to the read value
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 217 of file V8100.c.
References V8100_data::m_common_data, send_cmd(), and V8100_CMD_CH_MON_VMIN.
BOOL V8100_mon_vmon (V8100_data * p_data, UINT8 ch_id, float * value, CMD_ERROR_CODE * error_code)
Gets the value of the voltage Monitor.
Parameters:
p_data Pointer to board data
ch_id The channel identifier
value The pointer to the read value
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 252 of file V8100.c.
References V8100_data::m_common_data, send_cmd(), and V8100_CMD_CH_MON_VMON.
BOOL V8100_mon_vpmax (V8100_data * p_data, float * value, CMD_ERROR_CODE * error_code)
Gets the value maximum of OVP/UVP.
Parameters:
p_data Pointer to board data
value The pointer to the read value
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 458 of file V8100.c.
References V8100_data::m_common_data, send_cmd(), V8100_CMD_CR_MON_VPMAX, and V8100_CR_CH_ID.
BOOL V8100_mon_vpmin (V8100_data * p_data, float * value, CMD_ERROR_CODE * error_code)
Gets the value minimum of OVP/UVP.
Parameters:
p_data Pointer to board data
value The pointer to the read value
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 465 of file V8100.c.
References V8100_data::m_common_data, send_cmd(), V8100_CMD_CR_MON_VPMIN, and V8100_CR_CH_ID.
BOOL V8100_mon_vres (V8100_data * p_data, UINT8 ch_id, float * value, CMD_ERROR_CODE * error_code)
Gets the resolution value of the voltage Set.
Parameters:
p_data Pointer to board data
ch_id The channel identifier
value The pointer to the read value
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 231 of file V8100.c.
References V8100_data::m_common_data, send_cmd(), and V8100_CMD_CH_MON_VRES.
BOOL V8100_mon_vset (V8100_data * p_data, UINT8 ch_id, float * value, CMD_ERROR_CODE * error_code)
Gets the value of the voltage Set.
Parameters:
p_data Pointer to board data
ch_id The channel identifier
value The pointer to the read value
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 210 of file V8100.c.
References V8100_data::m_common_data, send_cmd(), and V8100_CMD_CH_MON_VSET.
BOOL V8100_open_com (V8100_data * p_data, const char * com_str, V8100_RS232_BITRATE bitrate)
V8100 boards data initialization and serial communication device opening.
Provides specific handling for V8100 boards opening on serial communication device.
Parameters:
p_data Pointer to board data
com_str The serial communication device to open e.g COM1.. COM# for Windows or /dev/ttyS0.. /dev/ttyS# or /dev/ttyUSB0.. /dev/ttyUSB# for Linux
bitrate The serial device communication baudrate
Returns:
TRUE: board successfully opened
Note:
Must be called before any other board specific API.
Definition at line 105 of file V8100.c.
References board_open(), FALSE, V8100_data::m_common_data, and TRUE.
BOOL V8100_open_eth (V8100_data * p_data, const char * ip_add)
V8100 boards data initialization and socket communication device opening.
Provides specific handling for V8100 boards opening on socket communication device.
Parameters:
p_data Pointer to board data
ip_add The crate ip address expressed as four eight-bit octets e.g xxx.xxx.xxx.xxx
Returns:
TRUE: board successfully opened
Note:
Must be called before any other board specific API.
Definition at line 157 of file V8100.c.
References board_open(), FALSE, V8100_data::m_common_data, and TRUE.
BOOL V8100_set_clr (V8100_data * p_data, CMD_ERROR_CODE * error_code)
Clear Alarm.
Parameters:
p_data Pointer to board data
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 555 of file V8100.c.
References V8100_data::m_common_data, send_cmd(), V8100_CMD_CR_SET_CLR, and V8100_CR_CH_ID.
BOOL V8100_set_fansp (V8100_data * p_data, V8100_FAN_SPEED_SET value, CMD_ERROR_CODE * error_code)
Set Fan Speed _V8100_FAN_SPEED_SET.
Parameters:
p_data Pointer to board data
value The value to set
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 562 of file V8100.c.
References V8100_data::m_common_data, send_cmd(), V8100_CMD_CR_SET_FANSP, and V8100_CR_CH_ID.
BOOL V8100_set_iset (V8100_data * p_data, UINT8 ch_id, float value, CMD_ERROR_CODE * error_code)
Sets the value of current limit.
Parameters:
p_data Pointer to board data
ch_id The channel identifier
value The value to set
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 316 of file V8100.c.
References V8100_data::m_common_data, send_cmd(), and V8100_CMD_CH_SET_ISET.
BOOL V8100_set_off (V8100_data * p_data, CMD_ERROR_CODE * error_code)
Switches the crate OFF.
Parameters:
p_data Pointer to board data
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 541 of file V8100.c.
References V8100_data::m_common_data, send_cmd(), V8100_CMD_CR_SET_OFF, and V8100_CR_CH_ID.
BOOL V8100_set_on (V8100_data * p_data, CMD_ERROR_CODE * error_code)
Switches the crate ON.
Parameters:
p_data Pointer to board data
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 534 of file V8100.c.
References V8100_data::m_common_data, send_cmd(), V8100_CMD_CR_SET_ON, and V8100_CR_CH_ID.
BOOL V8100_set_ovp (V8100_data * p_data, UINT8 ch_id, UINT8 value, CMD_ERROR_CODE * error_code)
Sets the value of Value OVP (as % di Vset).
Parameters:
p_data Pointer to board data
ch_id The channel identifier
value The value to set
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 323 of file V8100.c.
References V8100_data::m_common_data, send_cmd(), and V8100_CMD_CH_SET_OVP.
BOOL V8100_set_sysr (V8100_data * p_data, CMD_ERROR_CODE * error_code)
Sends VME System Reset.
Parameters:
p_data Pointer to board data
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 548 of file V8100.c.
References V8100_data::m_common_data, send_cmd(), V8100_CMD_CR_SET_SYSR, and V8100_CR_CH_ID.
BOOL V8100_set_uvp (V8100_data * p_data, UINT8 ch_id, UINT8 value, CMD_ERROR_CODE * error_code)
Sets the value of Value UVP (as % di Vset).
Parameters:
p_data Pointer to board data
ch_id The channel identifier
value The value to set
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 331 of file V8100.c.
References V8100_data::m_common_data, send_cmd(), and V8100_CMD_CH_SET_UVP.
BOOL V8100_set_vset (V8100_data * p_data, UINT8 ch_id, float value, CMD_ERROR_CODE * error_code)
Sets the value of voltage.
Parameters:
p_data Pointer to board data
ch_id The channel identifier
value The value to set
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 309 of file V8100.c.
References V8100_data::m_common_data, send_cmd(), and V8100_CMD_CH_SET_VSET.
const char * V8100_SW_rev (void)
Returns the SDK software release.
Returns:
const char*: The SDK revision string
Definition at line 583 of file V8100.c.