CAEN V8100 SDK: V8100.h File Reference
V8100.h File Reference
V8100 board definitions.
#include "../common/common_defs.h"
#include "../common/board_commons.h"
Data Structures
struct V8100_data
V8100 board data structure.
union V8100_channel_status
V8100 channel status as word and as bitfields.
union V8100_crate_status
V8100 crate status as word and as bitfields.
Defines
#define V8100_CR_CH_ID 8
The V8100 crate channel identifier.
#define V8100_MAX_CH 8
The V8100 crate maximum channels' number.
Enumerations
enum _V8100_COMMANDS {
V8100_CMD_CH_MON_NAME = 0, V8100_CMD_CH_MON_VSET, V8100_CMD_CH_MON_VMIN, V8100_CMD_CH_MON_VMAX,
V8100_CMD_CH_MON_VRES, V8100_CMD_CH_MON_OVP, V8100_CMD_CH_MON_UVP, V8100_CMD_CH_MON_VMON,
V8100_CMD_CH_MON_ISET, V8100_CMD_CH_MON_IMIN, V8100_CMD_CH_MON_IMAX, V8100_CMD_CH_MON_IRES,
V8100_CMD_CH_MON_IMON, V8100_CMD_CH_MON_STAT, V8100_CMD_CH_SET_VSET, V8100_CMD_CH_SET_ISET,
V8100_CMD_CH_SET_OVP, V8100_CMD_CH_SET_UVP, V8100_CMD_CR_MON_CRNAME, V8100_CMD_CR_MON_NUMCH,
V8100_CMD_CR_MON_PSFREL, V8100_CMD_CR_MON_PSTEMP, V8100_CMD_CR_MON_PSSNUM, V8100_CMD_CR_MON_FANSP,
V8100_CMD_CR_MON_FAN1, V8100_CMD_CR_MON_FAN2, V8100_CMD_CR_MON_FAN3, V8100_CMD_CR_MON_FUFREL,
V8100_CMD_CR_MON_FUTEMP, V8100_CMD_CR_MON_FUSNUM, V8100_CMD_CR_MON_CRST, V8100_CMD_CR_MON_VPMAX,
V8100_CMD_CR_MON_VPMIN, V8100_CMD_CR_MON_RS232BR, V8100_CMD_CR_MON_CANBR, V8100_CMD_CR_MON_CANADD,
V8100_CMD_CR_MON_IPADD, V8100_CMD_CR_MON_IPMSK, V8100_CMD_CR_MON_IPGTW, V8100_CMD_CR_MON_MACADD,
V8100_CMD_CR_SET_ON, V8100_CMD_CR_SET_OFF, V8100_CMD_CR_SET_SYSR, V8100_CMD_CR_SET_CLR,
V8100_CMD_CR_SET_FANSP
}
The board commands.
enum _V8100_RS232_BITRATE
RS232 bitrate values.
enum _V8100_CANBUS_BITRATE
CANBUS bitrate values.
enum _V8100_FAN_SPEED_SET { V8100_FANSP_OFF = 0 }
Fan speed setting values (RPMs).
Functions
DLL_API BOOL V8100_open_com (V8100_data *p_data, const char *com_str, V8100_RS232_BITRATE bitrate)
V8100 boards data initialization and serial communication device opening.
DLL_API BOOL V8100_open_eth (V8100_data *p_data, const char *ip_add)
V8100 boards data initialization and socket communication device opening.
DLL_API BOOL V8100_close (V8100_data *p_data)
V8100 boards closing and resource free.
DLL_API BOOL V8100_mon_name (V8100_data *p_data, UINT8 ch_id, char *value, int value_size, CMD_ERROR_CODE *error_code)
Gets the channel name.
DLL_API BOOL V8100_mon_vset (V8100_data *p_data, UINT8 ch_id, float *value, CMD_ERROR_CODE *error_code)
Gets the value of the voltage Set.
DLL_API BOOL V8100_mon_vmin (V8100_data *p_data, UINT8 ch_id, float *value, CMD_ERROR_CODE *error_code)
Gets the minimum value of the voltage Set.
DLL_API BOOL V8100_mon_vmax (V8100_data *p_data, UINT8 ch_id, float *value, CMD_ERROR_CODE *error_code)
Gets the maximum value of the voltage Set.
DLL_API BOOL V8100_mon_vres (V8100_data *p_data, UINT8 ch_id, float *value, CMD_ERROR_CODE *error_code)
Gets the resolution value of the voltage Set.
DLL_API BOOL V8100_mon_ovp (V8100_data *p_data, UINT8 ch_id, float *value, CMD_ERROR_CODE *error_code)
Gets the value of the Over Voltage Protection.
DLL_API BOOL V8100_mon_uvp (V8100_data *p_data, UINT8 ch_id, float *value, CMD_ERROR_CODE *error_code)
Gets the value of the Under Voltage Protection.
DLL_API BOOL V8100_mon_vmon (V8100_data *p_data, UINT8 ch_id, float *value, CMD_ERROR_CODE *error_code)
Gets the value of the voltage Monitor.
DLL_API BOOL V8100_mon_iset (V8100_data *p_data, UINT8 ch_id, float *value, CMD_ERROR_CODE *error_code)
Gets the value of the current limit.
DLL_API BOOL V8100_mon_imin (V8100_data *p_data, UINT8 ch_id, float *value, CMD_ERROR_CODE *error_code)
Gets the minimum value of current limit.
DLL_API BOOL V8100_mon_imax (V8100_data *p_data, UINT8 ch_id, float *value, CMD_ERROR_CODE *error_code)
Gets the maximum value of current limit.
DLL_API BOOL V8100_mon_ires (V8100_data *p_data, UINT8 ch_id, float *value, CMD_ERROR_CODE *error_code)
Gets the resolution of current limit.
DLL_API BOOL V8100_mon_imon (V8100_data *p_data, UINT8 ch_id, float *value, CMD_ERROR_CODE *error_code)
Gets the value of the current Monitor.
DLL_API BOOL V8100_mon_stat (V8100_data *p_data, UINT8 ch_id, V8100_channel_status *value, CMD_ERROR_CODE *error_code)
Gets the value of the channel status.
DLL_API BOOL V8100_set_vset (V8100_data *p_data, UINT8 ch_id, float value, CMD_ERROR_CODE *error_code)
Sets the value of voltage.
DLL_API BOOL V8100_set_iset (V8100_data *p_data, UINT8 ch_id, float value, CMD_ERROR_CODE *error_code)
Sets the value of current limit.
DLL_API BOOL V8100_set_ovp (V8100_data *p_data, UINT8 ch_id, UINT8 value, CMD_ERROR_CODE *error_code)
Sets the value of Value OVP (as % di Vset).
DLL_API BOOL V8100_set_uvp (V8100_data *p_data, UINT8 ch_id, UINT8 value, CMD_ERROR_CODE *error_code)
Sets the value of Value UVP (as % di Vset).
DLL_API BOOL V8100_mon_crname (V8100_data *p_data, char *value, int value_size, CMD_ERROR_CODE *error_code)
Gets the crate name.
DLL_API BOOL V8100_mon_numch (V8100_data *p_data, UINT8 *value, CMD_ERROR_CODE *error_code)
Gets the value of the voltage Set.
DLL_API BOOL V8100_mon_psfrel (V8100_data *p_data, char *value, int value_size, CMD_ERROR_CODE *error_code)
Gets the PS Release Firmware.
DLL_API BOOL V8100_mon_pstemp (V8100_data *p_data, float *value, CMD_ERROR_CODE *error_code)
Gets the value of the PS Temperature.
DLL_API BOOL V8100_mon_pssnum (V8100_data *p_data, UINT32 *value, CMD_ERROR_CODE *error_code)
Gets the value of the PS Serial Number.
DLL_API BOOL V8100_mon_fansp (V8100_data *p_data, V8100_FAN_SPEED_SET *value, CMD_ERROR_CODE *error_code)
Gets the Set value of FAN SPEED _V8100_FAN_SPEED_SET.
DLL_API BOOL V8100_mon_fan1 (V8100_data *p_data, UINT32 *value, CMD_ERROR_CODE *error_code)
Gets the value of the Fan Speed 1 (RPM).
DLL_API BOOL V8100_mon_fan2 (V8100_data *p_data, UINT32 *value, CMD_ERROR_CODE *error_code)
Gets the value of the Fan Speed 2 (RPM).
DLL_API BOOL V8100_mon_fan3 (V8100_data *p_data, UINT32 *value, CMD_ERROR_CODE *error_code)
Gets the value of the Fan Speed 3 (RPM).
DLL_API BOOL V8100_mon_fufrel (V8100_data *p_data, char *value, int value_size, CMD_ERROR_CODE *error_code)
Gets the FAN UNIT Release Firmware.
DLL_API BOOL V8100_mon_futemp (V8100_data *p_data, float *value, CMD_ERROR_CODE *error_code)
Gets the value of the FAN UNIT Temperature.
DLL_API BOOL V8100_mon_fusnum (V8100_data *p_data, UINT32 *value, CMD_ERROR_CODE *error_code)
Gets the value of the FAN UNIT Serial Number.
DLL_API BOOL V8100_mon_crst (V8100_data *p_data, V8100_crate_status *value, CMD_ERROR_CODE *error_code)
Gets the value of the crate status.
DLL_API BOOL V8100_mon_vpmax (V8100_data *p_data, float *value, CMD_ERROR_CODE *error_code)
Gets the value maximum of OVP/UVP.
DLL_API BOOL V8100_mon_vpmin (V8100_data *p_data, float *value, CMD_ERROR_CODE *error_code)
Gets the value minimum of OVP/UVP.
DLL_API BOOL V8100_mon_rs232br (V8100_data *p_data, V8100_RS232_BITRATE *value, CMD_ERROR_CODE *error_code)
Gets the value of Bit Rate RS232 : _V8100_RS232_BITRATE.
DLL_API BOOL V8100_mon_canbr (V8100_data *p_data, V8100_CANBUS_BITRATE *value, CMD_ERROR_CODE *error_code)
Gets the value of Bit Rate CANBUS : _V8100_CANBUS_BITRATE.
DLL_API BOOL V8100_mon_canadd (V8100_data *p_data, UINT8 *value, CMD_ERROR_CODE *error_code)
Gets the Address CANBUS : 0..255.
DLL_API BOOL V8100_mon_ipadd (V8100_data *p_data, char *value, int value_size, CMD_ERROR_CODE *error_code)
Gets the Address IP : xxx.xxx.xxx.xxx.
DLL_API BOOL V8100_mon_ipmsk (V8100_data *p_data, char *value, int value_size, CMD_ERROR_CODE *error_code)
Gets the IP Netmask : xxx.xxx.xxx.xxx.
DLL_API BOOL V8100_mon_ipgtw (V8100_data *p_data, char *value, int value_size, CMD_ERROR_CODE *error_code)
Gets the Gateway : xxx.xxx.xxx.xxx.
DLL_API BOOL V8100_mon_macadd (V8100_data *p_data, char *value, int value_size, CMD_ERROR_CODE *error_code)
Gets the Mac Address : xx.xx.xx.xx.xx.xx.
DLL_API BOOL V8100_set_on (V8100_data *p_data, CMD_ERROR_CODE *error_code)
Switches the crate ON.
DLL_API BOOL V8100_set_off (V8100_data *p_data, CMD_ERROR_CODE *error_code)
Switches the crate OFF.
DLL_API BOOL V8100_set_sysr (V8100_data *p_data, CMD_ERROR_CODE *error_code)
Sends VME System Reset.
DLL_API BOOL V8100_set_clr (V8100_data *p_data, CMD_ERROR_CODE *error_code)
Clear Alarm.
DLL_API BOOL V8100_set_fansp (V8100_data *p_data, V8100_FAN_SPEED_SET value, CMD_ERROR_CODE *error_code)
Set Fan Speed _V8100_FAN_SPEED_SET.
DLL_API const char * V8100_SW_rev (void)
Returns the SDK software release.
Detailed Description
V8100 board definitions.
Author:
NDA
Version:
1.0
Date:
09/2008
Provides methods, properties and defines to handle V8100 boards
Definition in file V8100.h.
Enumeration Type Documentation
enum _V8100_COMMANDS
The board commands.
Provides an entry for supported command: keep synched with cmd_table V8100_CMD_TABLE[ ]
Enumerator:
V8100_CMD_CH_MON_NAME Readout channel name (ex. +5V..).
V8100_CMD_CH_MON_VSET Readout value of the voltage Set.
V8100_CMD_CH_MON_VMIN Readout minimum value of the voltage Set.
V8100_CMD_CH_MON_VMAX Readout maximum value of the voltage Set.
V8100_CMD_CH_MON_VRES Readout resolution value of the voltage Set.
V8100_CMD_CH_MON_OVP Readout value Over Voltage Protection.
V8100_CMD_CH_MON_UVP Readout value Under Voltage Protection.
V8100_CMD_CH_MON_VMON Readout value of the voltage Monitor.
V8100_CMD_CH_MON_ISET Readout value of current limit.
V8100_CMD_CH_MON_IMIN Readout minimum value of current limit.
V8100_CMD_CH_MON_IMAX Readout maximum value of current limit.
V8100_CMD_CH_MON_IRES Readout value resolution of current limit.
V8100_CMD_CH_MON_IMON Readout value of the current Monitor.
V8100_CMD_CH_MON_STAT Readout value of channel status.
V8100_CMD_CH_SET_VSET Set voltage Value.
V8100_CMD_CH_SET_ISET Set Value of current limit.
V8100_CMD_CH_SET_OVP Set Value OVP (in % di Vset).
V8100_CMD_CH_SET_UVP Set Value UVP (in % di Vset).
V8100_CMD_CR_MON_CRNAME Readout Crate name : 'VME8100'.
V8100_CMD_CR_MON_NUMCH Readout number of channels present.
V8100_CMD_CR_MON_PSFREL Readout of the PS Release Firmware.
V8100_CMD_CR_MON_PSTEMP Readout of the PS Temperature.
V8100_CMD_CR_MON_PSSNUM Readout of the PS serial number.
V8100_CMD_CR_MON_FANSP Readout Set value of FAN SPEED (0..6).
V8100_CMD_CR_MON_FAN1 Readout value Fan Speed 1 (RPM).
V8100_CMD_CR_MON_FAN2 Readout value Fan Speed 2 (RPM).
V8100_CMD_CR_MON_FAN3 Readout value Fan Speed 3 (RPM).
V8100_CMD_CR_MON_FUFREL Readout of the FAN UNIT Release Firmware.
V8100_CMD_CR_MON_FUTEMP Readout of the FAN UNIT Temperature.
V8100_CMD_CR_MON_FUSNUM Readout of the FAN UNIT serial number.
V8100_CMD_CR_MON_CRST Readout value Crate status.
V8100_CMD_CR_MON_VPMAX Readout value maximum of OVP/UVP.
V8100_CMD_CR_MON_VPMIN Readout value minimum of OVP/UVP.
V8100_CMD_CR_MON_RS232BR Readout Bit Rate RS232 : 0..4.
V8100_CMD_CR_MON_CANBR Readout Bit Rate CANBUS : 0..5.
V8100_CMD_CR_MON_CANADD Readout Address CANBUS : 0..255.
V8100_CMD_CR_MON_IPADD Readout Address IP : xxx.xxx.xxx.xxx.
V8100_CMD_CR_MON_IPMSK Readout IP Netmask : xxx.xxx.xxx.xxx.
V8100_CMD_CR_MON_IPGTW Readout Gateway : xxx.xxx.xxx.xxx.
V8100_CMD_CR_MON_MACADD Readout Mac Address : xx.xx.xx.xx.xx.xx.
V8100_CMD_CR_SET_ON Crate ON.
V8100_CMD_CR_SET_OFF Crate OFF.
V8100_CMD_CR_SET_SYSR Sends VME System Reset.
V8100_CMD_CR_SET_CLR Clear Alarm.
V8100_CMD_CR_SET_FANSP Set Fan Speed. Values 0..6.
Definition at line 108 of file V8100.h.
enum _V8100_FAN_SPEED_SET
Fan speed setting values (RPMs).
Enumerator:
V8100_FANSP_OFF Fan OFF.
Definition at line 200 of file V8100.h.
Function Documentation
DLL_API BOOL V8100_close (V8100_data * p_data)
V8100 boards closing and resource free.
Provides specific handling for V8100 boards closing.
Parameters:
p_data Pointer to board data
Returns:
TRUE: board successfully closed
Note:
Must be called when done with any other board specific API.
Definition at line 183 of file V8100.c.
References board_close(), and V8100_data::m_common_data.
DLL_API BOOL V8100_mon_canadd (V8100_data * p_data, UINT8 * value, CMD_ERROR_CODE * error_code)
Gets the Address CANBUS : 0..255.
Parameters:
p_data Pointer to board data
value The pointer to the read value
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 492 of file V8100.c.
References V8100_data::m_common_data, send_cmd(), V8100_CMD_CR_MON_CANADD, and V8100_CR_CH_ID.
DLL_API BOOL V8100_mon_canbr (V8100_data * p_data, V8100_CANBUS_BITRATE * value, CMD_ERROR_CODE * error_code)
Gets the value of Bit Rate CANBUS : _V8100_CANBUS_BITRATE.
Parameters:
p_data Pointer to board data
value The pointer to the read value
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 482 of file V8100.c.
References V8100_data::m_common_data, send_cmd(), V8100_CMD_CR_MON_CANBR, and V8100_CR_CH_ID.
DLL_API BOOL V8100_mon_crname (V8100_data * p_data, char * value, int value_size, CMD_ERROR_CODE * error_code)
Gets the crate name.
Parameters:
p_data Pointer to board data
value The read value buffer (caller allocated)
value_size The value buffer size (BYTEs)
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 343 of file V8100.c.
References V8100_data::m_common_data, send_cmd(), V8100_CMD_CR_MON_CRNAME, and V8100_CR_CH_ID.
DLL_API BOOL V8100_mon_crst (V8100_data * p_data, V8100_crate_status * value, CMD_ERROR_CODE * error_code)
Gets the value of the crate status.
Parameters:
p_data Pointer to board data
value The pointer to the read value (V8100_crate_status)
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 448 of file V8100.c.
References V8100_data::m_common_data, V8100_crate_status::m_word, send_cmd(), V8100_CMD_CR_MON_CRST, and V8100_CR_CH_ID.
DLL_API BOOL V8100_mon_fan1 (V8100_data * p_data, UINT32 * value, CMD_ERROR_CODE * error_code)
Gets the value of the Fan Speed 1 (RPM).
Parameters:
p_data Pointer to board data
value The pointer to the read value
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 394 of file V8100.c.
References V8100_data::m_common_data, send_cmd(), V8100_CMD_CR_MON_FAN1, and V8100_CR_CH_ID.
DLL_API BOOL V8100_mon_fan2 (V8100_data * p_data, UINT32 * value, CMD_ERROR_CODE * error_code)
Gets the value of the Fan Speed 2 (RPM).
Parameters:
p_data Pointer to board data
value The pointer to the read value
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 404 of file V8100.c.
References V8100_data::m_common_data, send_cmd(), V8100_CMD_CR_MON_FAN2, and V8100_CR_CH_ID.
DLL_API BOOL V8100_mon_fan3 (V8100_data * p_data, UINT32 * value, CMD_ERROR_CODE * error_code)
Gets the value of the Fan Speed 3 (RPM).
Parameters:
p_data Pointer to board data
value The pointer to the read value
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 414 of file V8100.c.
References V8100_data::m_common_data, send_cmd(), V8100_CMD_CR_MON_FAN3, and V8100_CR_CH_ID.
DLL_API BOOL V8100_mon_fansp (V8100_data * p_data, V8100_FAN_SPEED_SET * value, CMD_ERROR_CODE * error_code)
Gets the Set value of FAN SPEED _V8100_FAN_SPEED_SET.
Parameters:
p_data Pointer to board data
value The pointer to the read value
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 384 of file V8100.c.
References V8100_data::m_common_data, send_cmd(), V8100_CMD_CR_MON_FANSP, and V8100_CR_CH_ID.
DLL_API BOOL V8100_mon_fufrel (V8100_data * p_data, char * value, int value_size, CMD_ERROR_CODE * error_code)
Gets the FAN UNIT Release Firmware.
Parameters:
p_data Pointer to board data
value The read value buffer (caller allocated)
value_size The value buffer size (BYTEs)
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 424 of file V8100.c.
References V8100_data::m_common_data, send_cmd(), V8100_CMD_CR_MON_FUFREL, and V8100_CR_CH_ID.
DLL_API BOOL V8100_mon_fusnum (V8100_data * p_data, UINT32 * value, CMD_ERROR_CODE * error_code)
Gets the value of the FAN UNIT Serial Number.
Parameters:
p_data Pointer to board data
value The pointer to the read value
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 438 of file V8100.c.
References V8100_data::m_common_data, send_cmd(), V8100_CMD_CR_MON_FUSNUM, and V8100_CR_CH_ID.
DLL_API BOOL V8100_mon_futemp (V8100_data * p_data, float * value, CMD_ERROR_CODE * error_code)
Gets the value of the FAN UNIT Temperature.
Parameters:
p_data Pointer to board data
value The pointer to the read value
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 431 of file V8100.c.
References V8100_data::m_common_data, send_cmd(), V8100_CMD_CR_MON_FUTEMP, and V8100_CR_CH_ID.
DLL_API BOOL V8100_mon_imax (V8100_data * p_data, UINT8 ch_id, float * value, CMD_ERROR_CODE * error_code)
Gets the maximum value of current limit.
Parameters:
p_data Pointer to board data
ch_id The channel identifier
value The pointer to the read value
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 273 of file V8100.c.
References V8100_data::m_common_data, send_cmd(), and V8100_CMD_CH_MON_IMAX.
DLL_API BOOL V8100_mon_imin (V8100_data * p_data, UINT8 ch_id, float * value, CMD_ERROR_CODE * error_code)
Gets the minimum value of current limit.
Parameters:
p_data Pointer to board data
ch_id The channel identifier
value The pointer to the read value
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 266 of file V8100.c.
References V8100_data::m_common_data, send_cmd(), and V8100_CMD_CH_MON_IMIN.
DLL_API BOOL V8100_mon_imon (V8100_data * p_data, UINT8 ch_id, float * value, CMD_ERROR_CODE * error_code)
Gets the value of the current Monitor.
Parameters:
p_data Pointer to board data
ch_id The channel identifier
value The pointer to the read value
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 287 of file V8100.c.
References V8100_data::m_common_data, send_cmd(), and V8100_CMD_CH_MON_IMON.
DLL_API BOOL V8100_mon_ipadd (V8100_data * p_data, char * value, int value_size, CMD_ERROR_CODE * error_code)
Gets the Address IP : xxx.xxx.xxx.xxx.
Parameters:
p_data Pointer to board data
value The read value buffer (caller allocated)
value_size The value buffer size (BYTEs)
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 502 of file V8100.c.
References V8100_data::m_common_data, send_cmd(), V8100_CMD_CR_MON_IPADD, and V8100_CR_CH_ID.
DLL_API BOOL V8100_mon_ipgtw (V8100_data * p_data, char * value, int value_size, CMD_ERROR_CODE * error_code)
Gets the Gateway : xxx.xxx.xxx.xxx.
Parameters:
p_data Pointer to board data
value The read value buffer (caller allocated)
value_size The value buffer size (BYTEs)
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 516 of file V8100.c.
References V8100_data::m_common_data, send_cmd(), V8100_CMD_CR_MON_IPGTW, and V8100_CR_CH_ID.
DLL_API BOOL V8100_mon_ipmsk (V8100_data * p_data, char * value, int value_size, CMD_ERROR_CODE * error_code)
Gets the IP Netmask : xxx.xxx.xxx.xxx.
Parameters:
p_data Pointer to board data
value The read value buffer (caller allocated)
value_size The value buffer size (BYTEs)
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 509 of file V8100.c.
References V8100_data::m_common_data, send_cmd(), V8100_CMD_CR_MON_IPMSK, and V8100_CR_CH_ID.
DLL_API BOOL V8100_mon_ires (V8100_data * p_data, UINT8 ch_id, float * value, CMD_ERROR_CODE * error_code)
Gets the resolution of current limit.
Parameters:
p_data Pointer to board data
ch_id The channel identifier
value The pointer to the read value
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 280 of file V8100.c.
References V8100_data::m_common_data, send_cmd(), and V8100_CMD_CH_MON_IRES.
DLL_API BOOL V8100_mon_iset (V8100_data * p_data, UINT8 ch_id, float * value, CMD_ERROR_CODE * error_code)
Gets the value of the current limit.
Parameters:
p_data Pointer to board data
ch_id The channel identifier
value The pointer to the read value
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 259 of file V8100.c.
References V8100_data::m_common_data, send_cmd(), and V8100_CMD_CH_MON_ISET.
DLL_API BOOL V8100_mon_macadd (V8100_data * p_data, char * value, int value_size, CMD_ERROR_CODE * error_code)
Gets the Mac Address : xx.xx.xx.xx.xx.xx.
Parameters:
p_data Pointer to board data
value The read value buffer (caller allocated)
value_size The value buffer size (BYTEs)
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 523 of file V8100.c.
References V8100_data::m_common_data, send_cmd(), V8100_CMD_CR_MON_MACADD, and V8100_CR_CH_ID.
DLL_API BOOL V8100_mon_name (V8100_data * p_data, UINT8 ch_id, char * value, int value_size, CMD_ERROR_CODE * error_code)
Gets the channel name.
Parameters:
p_data Pointer to board data
ch_id The channel identifier
value The read value buffer (caller allocated)
value_size The value buffer size (BYTEs)
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 203 of file V8100.c.
References V8100_data::m_common_data, send_cmd(), and V8100_CMD_CH_MON_NAME.
DLL_API BOOL V8100_mon_numch (V8100_data * p_data, UINT8 * value, CMD_ERROR_CODE * error_code)
Gets the value of the voltage Set.
Parameters:
p_data Pointer to board data
value The pointer to the read value
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 350 of file V8100.c.
References V8100_data::m_common_data, send_cmd(), V8100_CMD_CR_MON_NUMCH, and V8100_CR_CH_ID.
DLL_API BOOL V8100_mon_ovp (V8100_data * p_data, UINT8 ch_id, float * value, CMD_ERROR_CODE * error_code)
Gets the value of the Over Voltage Protection.
Parameters:
p_data Pointer to board data
ch_id The channel identifier
value The pointer to the read value
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 238 of file V8100.c.
References V8100_data::m_common_data, send_cmd(), and V8100_CMD_CH_MON_OVP.
DLL_API BOOL V8100_mon_psfrel (V8100_data * p_data, char * value, int value_size, CMD_ERROR_CODE * error_code)
Gets the PS Release Firmware.
Parameters:
p_data Pointer to board data
value The read value buffer (caller allocated)
value_size The value buffer size (BYTEs)
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 360 of file V8100.c.
References V8100_data::m_common_data, send_cmd(), V8100_CMD_CR_MON_PSFREL, and V8100_CR_CH_ID.
DLL_API BOOL V8100_mon_pssnum (V8100_data * p_data, UINT32 * value, CMD_ERROR_CODE * error_code)
Gets the value of the PS Serial Number.
Parameters:
p_data Pointer to board data
value The pointer to the read value
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 374 of file V8100.c.
References V8100_data::m_common_data, send_cmd(), V8100_CMD_CR_MON_PSSNUM, and V8100_CR_CH_ID.
DLL_API BOOL V8100_mon_pstemp (V8100_data * p_data, float * value, CMD_ERROR_CODE * error_code)
Gets the value of the PS Temperature.
Parameters:
p_data Pointer to board data
value The pointer to the read value
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 367 of file V8100.c.
References V8100_data::m_common_data, send_cmd(), V8100_CMD_CR_MON_PSTEMP, and V8100_CR_CH_ID.
DLL_API BOOL V8100_mon_rs232br (V8100_data * p_data, V8100_RS232_BITRATE * value, CMD_ERROR_CODE * error_code)
Gets the value of Bit Rate RS232 : _V8100_RS232_BITRATE.
Parameters:
p_data Pointer to board data
value The pointer to the read value
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 472 of file V8100.c.
References V8100_data::m_common_data, send_cmd(), V8100_CMD_CR_MON_RS232BR, and V8100_CR_CH_ID.
DLL_API BOOL V8100_mon_stat (V8100_data * p_data, UINT8 ch_id, V8100_channel_status * value, CMD_ERROR_CODE * error_code)
Gets the value of the channel status.
Parameters:
p_data Pointer to board data
ch_id The channel identifier
value The pointer to the read value (V8100_channel_status)
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 294 of file V8100.c.
References V8100_data::m_common_data, V8100_channel_status::m_word, send_cmd(), and V8100_CMD_CH_MON_STAT.
DLL_API BOOL V8100_mon_uvp (V8100_data * p_data, UINT8 ch_id, float * value, CMD_ERROR_CODE * error_code)
Gets the value of the Under Voltage Protection.
Parameters:
p_data Pointer to board data
ch_id The channel identifier
value The pointer to the read value
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 245 of file V8100.c.
References V8100_data::m_common_data, send_cmd(), and V8100_CMD_CH_MON_UVP.
DLL_API BOOL V8100_mon_vmax (V8100_data * p_data, UINT8 ch_id, float * value, CMD_ERROR_CODE * error_code)
Gets the maximum value of the voltage Set.
Parameters:
p_data Pointer to board data
ch_id The channel identifier
value The pointer to the read value
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 224 of file V8100.c.
References V8100_data::m_common_data, send_cmd(), and V8100_CMD_CH_MON_VMAX.
DLL_API BOOL V8100_mon_vmin (V8100_data * p_data, UINT8 ch_id, float * value, CMD_ERROR_CODE * error_code)
Gets the minimum value of the voltage Set.
Parameters:
p_data Pointer to board data
ch_id The channel identifier
value The pointer to the read value
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 217 of file V8100.c.
References V8100_data::m_common_data, send_cmd(), and V8100_CMD_CH_MON_VMIN.
DLL_API BOOL V8100_mon_vmon (V8100_data * p_data, UINT8 ch_id, float * value, CMD_ERROR_CODE * error_code)
Gets the value of the voltage Monitor.
Parameters:
p_data Pointer to board data
ch_id The channel identifier
value The pointer to the read value
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 252 of file V8100.c.
References V8100_data::m_common_data, send_cmd(), and V8100_CMD_CH_MON_VMON.
DLL_API BOOL V8100_mon_vpmax (V8100_data * p_data, float * value, CMD_ERROR_CODE * error_code)
Gets the value maximum of OVP/UVP.
Parameters:
p_data Pointer to board data
value The pointer to the read value
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 458 of file V8100.c.
References V8100_data::m_common_data, send_cmd(), V8100_CMD_CR_MON_VPMAX, and V8100_CR_CH_ID.
DLL_API BOOL V8100_mon_vpmin (V8100_data * p_data, float * value, CMD_ERROR_CODE * error_code)
Gets the value minimum of OVP/UVP.
Parameters:
p_data Pointer to board data
value The pointer to the read value
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 465 of file V8100.c.
References V8100_data::m_common_data, send_cmd(), V8100_CMD_CR_MON_VPMIN, and V8100_CR_CH_ID.
DLL_API BOOL V8100_mon_vres (V8100_data * p_data, UINT8 ch_id, float * value, CMD_ERROR_CODE * error_code)
Gets the resolution value of the voltage Set.
Parameters:
p_data Pointer to board data
ch_id The channel identifier
value The pointer to the read value
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 231 of file V8100.c.
References V8100_data::m_common_data, send_cmd(), and V8100_CMD_CH_MON_VRES.
DLL_API BOOL V8100_mon_vset (V8100_data * p_data, UINT8 ch_id, float * value, CMD_ERROR_CODE * error_code)
Gets the value of the voltage Set.
Parameters:
p_data Pointer to board data
ch_id The channel identifier
value The pointer to the read value
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 210 of file V8100.c.
References V8100_data::m_common_data, send_cmd(), and V8100_CMD_CH_MON_VSET.
DLL_API BOOL V8100_open_com (V8100_data * p_data, const char * com_str, V8100_RS232_BITRATE bitrate)
V8100 boards data initialization and serial communication device opening.
Provides specific handling for V8100 boards opening on serial communication device.
Parameters:
p_data Pointer to board data
com_str The serial communication device to open e.g COM1.. COM# for Windows or /dev/ttyS0.. /dev/ttyS# or /dev/ttyUSB0.. /dev/ttyUSB# for Linux
bitrate The serial device communication baudrate
Returns:
TRUE: board successfully opened
Note:
Must be called before any other board specific API.
Definition at line 105 of file V8100.c.
References board_open(), FALSE, V8100_data::m_common_data, and TRUE.
DLL_API BOOL V8100_open_eth (V8100_data * p_data, const char * ip_add)
V8100 boards data initialization and socket communication device opening.
Provides specific handling for V8100 boards opening on socket communication device.
Parameters:
p_data Pointer to board data
ip_add The crate ip address expressed as four eight-bit octets e.g xxx.xxx.xxx.xxx
Returns:
TRUE: board successfully opened
Note:
Must be called before any other board specific API.
Definition at line 157 of file V8100.c.
References board_open(), FALSE, V8100_data::m_common_data, and TRUE.
DLL_API BOOL V8100_set_clr (V8100_data * p_data, CMD_ERROR_CODE * error_code)
Clear Alarm.
Parameters:
p_data Pointer to board data
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 555 of file V8100.c.
References V8100_data::m_common_data, send_cmd(), V8100_CMD_CR_SET_CLR, and V8100_CR_CH_ID.
DLL_API BOOL V8100_set_fansp (V8100_data * p_data, V8100_FAN_SPEED_SET value, CMD_ERROR_CODE * error_code)
Set Fan Speed _V8100_FAN_SPEED_SET.
Parameters:
p_data Pointer to board data
value The value to set
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 562 of file V8100.c.
References V8100_data::m_common_data, send_cmd(), V8100_CMD_CR_SET_FANSP, and V8100_CR_CH_ID.
DLL_API BOOL V8100_set_iset (V8100_data * p_data, UINT8 ch_id, float value, CMD_ERROR_CODE * error_code)
Sets the value of current limit.
Parameters:
p_data Pointer to board data
ch_id The channel identifier
value The value to set
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 316 of file V8100.c.
References V8100_data::m_common_data, send_cmd(), and V8100_CMD_CH_SET_ISET.
DLL_API BOOL V8100_set_off (V8100_data * p_data, CMD_ERROR_CODE * error_code)
Switches the crate OFF.
Parameters:
p_data Pointer to board data
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 541 of file V8100.c.
References V8100_data::m_common_data, send_cmd(), V8100_CMD_CR_SET_OFF, and V8100_CR_CH_ID.
DLL_API BOOL V8100_set_on (V8100_data * p_data, CMD_ERROR_CODE * error_code)
Switches the crate ON.
Parameters:
p_data Pointer to board data
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 534 of file V8100.c.
References V8100_data::m_common_data, send_cmd(), V8100_CMD_CR_SET_ON, and V8100_CR_CH_ID.
DLL_API BOOL V8100_set_ovp (V8100_data * p_data, UINT8 ch_id, UINT8 value, CMD_ERROR_CODE * error_code)
Sets the value of Value OVP (as % di Vset).
Parameters:
p_data Pointer to board data
ch_id The channel identifier
value The value to set
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 323 of file V8100.c.
References V8100_data::m_common_data, send_cmd(), and V8100_CMD_CH_SET_OVP.
DLL_API BOOL V8100_set_sysr (V8100_data * p_data, CMD_ERROR_CODE * error_code)
Sends VME System Reset.
Parameters:
p_data Pointer to board data
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 548 of file V8100.c.
References V8100_data::m_common_data, send_cmd(), V8100_CMD_CR_SET_SYSR, and V8100_CR_CH_ID.
DLL_API BOOL V8100_set_uvp (V8100_data * p_data, UINT8 ch_id, UINT8 value, CMD_ERROR_CODE * error_code)
Sets the value of Value UVP (as % di Vset).
Parameters:
p_data Pointer to board data
ch_id The channel identifier
value The value to set
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 331 of file V8100.c.
References V8100_data::m_common_data, send_cmd(), and V8100_CMD_CH_SET_UVP.
DLL_API BOOL V8100_set_vset (V8100_data * p_data, UINT8 ch_id, float value, CMD_ERROR_CODE * error_code)
Sets the value of voltage.
Parameters:
p_data Pointer to board data
ch_id The channel identifier
value The value to set
error_code The command result code (may be null)
Returns:
TRUE: operation successfully completed
Definition at line 309 of file V8100.c.
References V8100_data::m_common_data, send_cmd(), and V8100_CMD_CH_SET_VSET.
DLL_API const char* V8100_SW_rev (void)
Returns the SDK software release.
Returns:
const char*: The SDK revision string
Definition at line 583 of file V8100.c.