CAEN V8100 SDK: board_commons.h File Reference
board_commons.h File Reference
Board common features definitions.
#include <stdio.h>
#include "common_defs.h"
#include "com_phy_layer.h"
Data Structures
struct cmd_table
Board commands table entry.
struct board_data
Data common to every board.
Defines
#define CMD_ASW_OK "#CMD:OK"
Command answer Ok with no return value.
#define CMD_ASW_OK_INT "#CMD:OK,VAL:%d\r"
Command answer Ok with integer return value.
#define CMD_ASW_OK_FLOAT "#CMD:OK,VAL:%f\r"
Command answer Ok with floating point return value.
#define CMD_ASW_OK_STRING "#CMD:OK,VAL:%s\r"
Command answer Ok with string return value.
#define CMD_ASW_CMD_ERR "#CMD:ERR\r"
Command answer with command error.
#define CMD_ASW_CH_ERR "#CH:ERR\r"
Command answer with channel error.
#define CMD_ASW_PAR_ERR "#PAR:ERR\r"
Command answer with parameter error.
#define CMD_ASW_VAL_ERR "#VAL:ERR\r"
Command answer with value error.
Enumerations
enum _CMD_PARAM_TYPE { CMD_PTYPE_NONE = 0, CMD_PTYPE_INT, CMD_PTYPE_FLOAT, CMD_PTYPE_STRING }
The parameter type supported by a command.
enum _CMD_ERROR_CODE {
CMD_ERR_OK = 0, CMD_ERR_CMD, CMD_ERR_CH, CMD_ERR_PAR,
CMD_ERR_VAL, CMD_ERR_BADASW, CMD_ERR_TOUT, CMD_ERR_TX,
CMD_ERR_RX
}
Command answer error code.
Functions
UINT8 ror_bits (UINT8 data, int num_bits)
Perfoms a num_bits bitwise right rotation of data byte.
UINT8 swap_bits (UINT8 data)
Swaps the bits of the source byte.
void delay (int msec)
Waits for specified time.
UINT32 get_time ()
Gets the time in milliseconds since first procedure call.
DLL_API BOOL board_open (board_data *p_data, const CPLConfig *p_com_config, const cmd_table *p_cmd_table)
Basic board open.
DLL_API BOOL board_close (board_data *p_data)
Basic board close.
DLL_API const char * get_last_answer (board_data *p_data)
Get the answer to the last successfull sent command.
DLL_API CMD_ERROR_CODE get_last_error (board_data *p_data)
Get the last error code.
DLL_API BOOL send_buffer (board_data *p_data, const UINT8 *buff, UINT16 buff_size)
Sends a data buffer to board.
DLL_API BOOL receive_buffer (board_data *p_data, UINT8 *buff, UINT16 *buff_size, int timeout_msec)
Read up to *buff_size BYTEs from board.
DLL_API BOOL send_cmd (board_data *p_data, int cmd_index, int ch_index, const void *cmd_value, void *cmd_result, int cmd_result_size, CMD_ERROR_CODE *error_code)
Sends a command to the specified channel.
Detailed Description
Board common features definitions.
Author:
NDA
Version:
1.0
Date:
07/2008
Boards common APIs: typically level 0 APIs These APIs provide features common to every board.
Definition in file board_commons.h.
Enumeration Type Documentation
enum _CMD_ERROR_CODE
Command answer error code.
Enumerator:
CMD_ERR_OK No error , command successful.
CMD_ERR_CMD Command Format wrong or command not recognised.
CMD_ERR_CH Channel Field not present or channel value wrong.
CMD_ERR_PAR Field parameter not present or parameter not recognised.
CMD_ERR_VAL Set Value wrong.
CMD_ERR_BADASW Bad Answer format.
CMD_ERR_TOUT Answer timeout.
CMD_ERR_TX Error on TX.
CMD_ERR_RX Error on RX.
Definition at line 97 of file board_commons.h.
enum _CMD_PARAM_TYPE
The parameter type supported by a command.
Enumerator:
CMD_PTYPE_NONE The no parameter.
CMD_PTYPE_INT The one integer parameter.
CMD_PTYPE_FLOAT The one float parameter.
CMD_PTYPE_STRING The one string parameter.
Definition at line 84 of file board_commons.h.
Function Documentation
DLL_API BOOL board_close (board_data * p_data)
Basic board close.
Provides basic handling for board closing, common to all the boards. It tries to close the communication channel, too.
Parameters:
p_data Pointer to board data
Returns:
TRUE: board successfully closed
Note:
This API if typically called by derived boards during close procedure.
Definition at line 234 of file board_commons.c.
References FALSE, board_data::m_p_asw_buff, board_data::m_p_cpl_object, board_data::m_p_last_sent_cmd, board_data::m_p_tmp_asw_buff, and TRUE.
Referenced by V8100_close().
DLL_API BOOL board_open (board_data * p_data, const CPLConfig * p_com_config, const cmd_table * p_cmd_table)
Basic board open.
Provides basic handling for board opening, common to all the boards. It tries to open the communication channel, too.
Parameters:
p_data Pointer to board data
p_com_config The communication physical layer device settings
p_cmd_table The board specific command table pointer
Returns:
TRUE: board successfully opened
Note:
This API if typically called by derived boards during open procedure.
Definition at line 199 of file board_commons.c.
References FALSE, board_data::m_asw_buff_len, board_data::m_p_asw_buff, board_data::m_p_cmd_table, board_data::m_p_cpl_object, board_data::m_p_last_sent_cmd, board_data::m_p_tmp_asw_buff, and TRUE.
Referenced by V8100_open_com(), and V8100_open_eth().
void delay (int msec)
Waits for specified time.
Parameters:
msec The time delay to wait (msec)
Definition at line 74 of file board_commons.c.
DLL_API const char* get_last_answer (board_data * p_data)
Get the answer to the last successfull sent command.
Parameters:
p_data Pointer to board data
Returns:
The answer buffer
Definition at line 338 of file board_commons.c.
References board_data::m_asw_buff_len, board_data::m_p_asw_buff, and board_data::m_p_tmp_asw_buff.
DLL_API CMD_ERROR_CODE get_last_error (board_data * p_data)
Get the last error code.
Parameters:
p_data Pointer to board data
Returns:
The error code _CMD_ERROR_CODE
Definition at line 359 of file board_commons.c.
References board_data::m_last_cmd_err.
UINT32 get_time ()
Gets the time in milliseconds since first procedure call.
Returns:
The time in milliseconds since first procedure call
Definition at line 88 of file board_commons.c.
Referenced by receive_buffer().
DLL_API BOOL receive_buffer (board_data * p_data, UINT8 * buff, UINT16 * buff_size, int timeout_msec)
Read up to *buff_size BYTEs from board.
Parameters:
p_data Pointer to board data
buff The user allocated buffer
buff_size The user allocated buffer size (on enter) and the number of BYTEs read (on exit)
timeout_msec The timeout between bytes receive (msec)
Returns:
TRUE read procedure ok
Definition at line 294 of file board_commons.c.
References CMD_ERR_OK, CMD_ERR_RX, CMD_ERR_TOUT, FALSE, get_time(), board_data::m_asw_buff_len, board_data::m_last_cmd_err, board_data::m_p_cpl_object, and TRUE.
Referenced by send_cmd().
UINT8 ror_bits (UINT8 data, int num_bits)
Perfoms a num_bits bitwise right rotation of data byte.
Parameters:
data The source byte to rotate
num_bits The number of bits to rotate
Returns:
Converted data
Definition at line 48 of file board_commons.c.
DLL_API BOOL send_buffer (board_data * p_data, const UINT8 * buff, UINT16 buff_size)
Sends a data buffer to board.
Parameters:
p_data Pointer to board data
buff The data buffer to send
buff_size The data buffer size (BYTEs)
Returns:
TRUE send procedure ok
Definition at line 269 of file board_commons.c.
References CMD_ERR_OK, CMD_ERR_TX, FALSE, board_data::m_last_cmd_err, board_data::m_p_cpl_object, and TRUE.
Referenced by send_cmd().
DLL_API BOOL send_cmd (board_data * p_data, int cmd_index, int ch_index, const void * cmd_value, void * cmd_result, int cmd_result_size, CMD_ERROR_CODE * error_code)
Sends a command to the specified channel.
Sends a command to the specified channel and waits for the answer
Parameters:
p_data Pointer to board data
cmd_index The index of the command (as from the board specific COMMANDS enumerator)
ch_index The channel index to with send the command
cmd_value The command input parameter value's pointer according to the cmd_table format: may be null if no input parameter is required
cmd_result The command result value's pointer according to the cmd_table format: may be null if no result value is expected
cmd_result_size The cmd_result storage size : meaningful for CMD_PTYPE_STRING result only
error_code The communication error code pointer (my be null)
Returns:
TRUE send procedure ok
Definition at line 372 of file board_commons.c.
References CMD_ASW_CH_ERR, CMD_ASW_CMD_ERR, CMD_ASW_OK, CMD_ASW_OK_FLOAT, CMD_ASW_OK_INT, CMD_ASW_OK_STRING, CMD_ASW_PAR_ERR, CMD_ASW_VAL_ERR, CMD_ERR_BADASW, CMD_ERR_CH, CMD_ERR_CMD, CMD_ERR_OK, CMD_ERR_PAR, CMD_ERR_VAL, CMD_PTYPE_FLOAT, CMD_PTYPE_INT, CMD_PTYPE_NONE, CMD_PTYPE_STRING, FALSE, cmd_table::m_cmd_string, board_data::m_last_cmd_err, cmd_table::m_max_ch_index, cmd_table::m_max_value, cmd_table::m_min_ch_index, cmd_table::m_min_value, board_data::m_p_asw_buff, board_data::m_p_cmd_table, board_data::m_p_last_sent_cmd, cmd_table::m_param_type, cmd_table::m_result_type, receive_buffer(), send_buffer(), and TRUE.
Referenced by V8100_mon_canadd(), V8100_mon_canbr(), V8100_mon_crname(), V8100_mon_crst(), V8100_mon_fan1(), V8100_mon_fan2(), V8100_mon_fan3(), V8100_mon_fansp(), V8100_mon_fufrel(), V8100_mon_fusnum(), V8100_mon_futemp(), V8100_mon_imax(), V8100_mon_imin(), V8100_mon_imon(), V8100_mon_ipadd(), V8100_mon_ipgtw(), V8100_mon_ipmsk(), V8100_mon_ires(), V8100_mon_iset(), V8100_mon_macadd(), V8100_mon_name(), V8100_mon_numch(), V8100_mon_ovp(), V8100_mon_psfrel(), V8100_mon_pssnum(), V8100_mon_pstemp(), V8100_mon_rs232br(), V8100_mon_stat(), V8100_mon_uvp(), V8100_mon_vmax(), V8100_mon_vmin(), V8100_mon_vmon(), V8100_mon_vpmax(), V8100_mon_vpmin(), V8100_mon_vres(), V8100_mon_vset(), V8100_set_clr(), V8100_set_fansp(), V8100_set_iset(), V8100_set_off(), V8100_set_on(), V8100_set_ovp(), V8100_set_sysr(), V8100_set_uvp(), and V8100_set_vset().
UINT8 swap_bits (UINT8 data)
Swaps the bits of the source byte.
Parameters:
data The source byte to swap
Returns:
Converted data
Definition at line 60 of file board_commons.c.